### ISSUE TITLE
Curious about status / outdated dependencies

### ISSUE THREAD

**Issue by nsaunders** [iand675/growler#3]
This looks like a really nice API for building REST services. Unfortunately, it appears that some dependencies are pretty outdated, and I'm having trouble getting it installed via Stack as a result. (This is probably really easy to work around for some, but I'm a total Haskell rookie.) Is there still any interest in this project, or should I be looking at some alternative instead?

**Comment by iand675** [comment]
Hi there, I appreciate the interest in this! However, I really wouldn't recommend using `growler` at present. There simply hasn't been any ongoing development, and I currently use `yesod` for serious work. There is much more community development towards it, and it is more type-safe in a number of cases. If you don't need everything yesod has to offer, I'd suggest using the yesod-minimal stack template to start off and then selectively enable things.

**Comment by nsaunders** [comment]
Thanks very much for the response. I will check out Yesod for now.
